### ISSUE TITLE
Smtp stream_options not used when swiftmailer.url 

### ISSUE THREAD

**Issue by unkndono** [swiftmailer/swiftmailer#1108]
Hi everyone, 

| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Symfony 4.1
| Swiftmailer version | 6.1.1
| PHP version         | 7.2.4

### Observed behaviour
When using an amazon (internal) ses server via a url like this : 
```yaml
swiftmailer:
  stream_options: 
    ssl:
      allow_self_signed: true
      verify_peer: false
      verify_peer_name: false
  url: smtp://host?....
```
the transport object doesn't get the stream_options config value. Thus i got the common error:
Warning: stream_socket_enable_crypto(): Peer certificate CN=`email-smtp.eu-west-1.amazonaws.com' did not match expected CN=`myamazonsmtpserver'

If i hardcode the credentials in the swiftmailer config like below, it's working great (because i guess the setStreamOptions is indeed called for the _swiftmailer.mailer.default.transport.smtp_ service in the service container mechanism srcDevDebugProjectContainer.xml): 
```yaml
swiftmailer:
  stream_options:  ...
  host:       myHost
  username:   myUser
  password:   myPassword
  encryption: tls
etc....
```
### Expected behaviour
Set the stream_options on the smtp transport in any case

### Temporary fix
For the moment, i can force this just before sending my email : 
```php
$mailer->getTransport()->setStreamOptions(
            [
                "ssl" => [
                    "allow_self_signed" => true,
                    "verify_peer"       => false,
                    "verify_peer_name"  => false,
                ],
            ]
        );
```
