### ISSUE TITLE
Cannot bind Symfony service to custom mailer and override defaut mailer

### ISSUE THREAD

**Issue by ericjacolin** [swiftmailer/swiftmailer#1199]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Symfony
| Swiftmailer version | 6.2.1
| PHP version         | 7.2.19

### Observed behaviour
Symfony 4.3
I have defined two custom mailers:

```
#swiftmailer.yml:
swiftmailer:
    default_mailer: realtime_mailer
    mailers:
        realtime_mailer:
            transport: '%env(MAILER_TRANSPORT)%'
            auth_mode: login
            host: '%env(MAILER_HOST)%'
            port: '%env(MAILER_PORT)%'
            encryption: '%env(MAILER_ENCRYPTION)%'
            username: '%env(MAILER_USER)%'
            password: '%env(MAILER_PASSWORD)%'
            spool:
                type: file
                path: '%kernel.project_dir%/var/spool'
        batch_mailer:
            transport: '%env(MAILER_TRANSPORT)%'
            auth_mode: login
            host: '%env(MAILER_HOST)%'
            port: '%env(MAILER_PORT)%'
            encryption: '%env(MAILER_ENCRYPTION)%'
            username: '%env(MAILER_USER)%'
            password: '%env(MAILER_PASSWORD)%'
            spool:
                type: file
                path: '%kernel.project_dir%/var/spool'
```
I tried to bind Swift_Mailer to one of these custom mailers:

```
#services.yml
services:
        bind:
            \Swift_Mailer: '@swiftmailer.mailer.realtime_mailer'
```

### Expected behaviour
When injected in a controller, the \Swift_Mailer service still refers to the default mailer.
I verified this with 
```
$ bin/console debug:container | grep mailer
  Swift_Mailer                                                                         alias for "swiftmailer.mailer.default"                                                          
  Swift_Transport                                                                      alias for "swiftmailer.mailer.default.transport.smtp"                                           
  mailer                                                                               alias for "swiftmailer.mailer.default"                                                          
  swiftmailer.command.debug                                                            Symfony\Bundle\SwiftmailerBundle\Command\DebugCommand                                           
  swiftmailer.command.new_email                                                        Symfony\Bundle\SwiftmailerBundle\Command\NewEmailCommand                                        
  swiftmailer.command.send_email                                                       Symfony\Bundle\SwiftmailerBundle\Command\SendEmailCommand                                       
  swiftmailer.data_collector                                                           Symfony\Bundle\SwiftmailerBundle\DataCollector\MessageDataCollector                             
  swiftmailer.email_sender.listener                                                    Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener                              
  swiftmailer.mailer                                                                   alias for "swiftmailer.mailer.default"                                                          
  swiftmailer.mailer.abstract                                                          Swift_Mailer                                                                                    
  swiftmailer.mailer.batch_mailer                                                      Swift_Mailer                                                                                    
  swiftmailer.mailer.batch_mailer.plugin.messagelogger                                 Swift_Plugins_MessageLogger                                                                     
  swiftmailer.mailer.batch_mailer.spool                                                alias for "swiftmailer.mailer.batch_mailer.spool.file"                                          
  swiftmailer.mailer.batch_mailer.spool.file                                           Swift_FileSpool                                                                                 
  swiftmailer.mailer.batch_mailer.transport                                            alias for "swiftmailer.mailer.batch_mailer.transport.spool"                                     
  swiftmailer.mailer.batch_mailer.transport.dynamic                                    Swift_Transport                                                                                 
  swiftmailer.mailer.batch_mailer.transport.eventdispatcher                            Swift_Events_SimpleEventDispatcher                                                              
  swiftmailer.mailer.batch_mailer.transport.real                                       alias for "swiftmailer.mailer.batch_mailer.transport.dynamic"                                   
  swiftmailer.mailer.batch_mailer.transport.spool                                      Swift_Transport_SpoolTransport                                                                  
  swiftmailer.mailer.default                                                           Swift_Mailer                                                                                    
  swiftmailer.mailer.default.plugin.messagelogger                                      Swift_Plugins_MessageLogger                                                                     
  swiftmailer.mailer.default.plugin.redirecting                                        Swift_Plugins_RedirectingPlugin                                                                 
  swiftmailer.mailer.default.transport                                                 alias for "swiftmailer.mailer.default.transport.smtp"                                           
  swiftmailer.mailer.default.transport.authhandler                                     Swift_Transport_Esmtp_AuthHandler                                                               
  swiftmailer.mailer.default.transport.buffer                                          Swift_Transport_StreamBuffer                                                                    
  swiftmailer.mailer.default.transport.eventdispatcher                                 Swift_Events_SimpleEventDispatcher                                                              
  swiftmailer.mailer.default.transport.smtp                                            Swift_Transport_EsmtpTransport                                                                  
  swiftmailer.mailer.realtime_mailer                                                   Swift_Mailer                                                                                    
  swiftmailer.mailer.realtime_mailer.plugin.messagelogger                              Swift_Plugins_MessageLogger                                                                     
  swiftmailer.mailer.realtime_mailer.spool                                             alias for "swiftmailer.mailer.realtime_mailer.spool.file"                                       
  swiftmailer.mailer.realtime_mailer.spool.file                                        Swift_FileSpool                                                                                 
  swiftmailer.mailer.realtime_mailer.transport                                         alias for "swiftmailer.mailer.realtime_mailer.transport.spool"                                  
  swiftmailer.mailer.realtime_mailer.transport.dynamic                                 Swift_Transport                                                                                 
  swiftmailer.mailer.realtime_mailer.transport.eventdispatcher                         Swift_Events_SimpleEventDispatcher                                                              
  swiftmailer.mailer.realtime_mailer.transport.real                                    alias for "swiftmailer.mailer.realtime_mailer.transport.dynamic"                                
```
The default mailer remains defined, not overridden by the swiftmailer.default_mailer configuration,  and the \Swift_Mailer Symfony service is not bound to the custom mailer either.
