### ISSUE TITLE
Unable to Send SSL Encrypted Mails 

### ISSUE THREAD

**Issue by ArchTaqi** [swiftmailer/swiftmailer#1246]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| RFC?                | yes/no
| How used?           | Symfony v3.4.14
| Swiftmailer version | v5.4.12
| PHP version         | 7.2

I'm trying to send out mails as SSL Encryption with Swiftmailer, I have below configuration
```yaml
transport: smtp
host:    smtp.service.company.com
username:  "%mailer_user%"
password:  "%mailer_password%"
encryption: ssl
auth_mode: login
port: 465
stream-options:
    ssl:
        allow_self_signed: true
        verify_peer: false
spool:
    type: file
    path: "%mailer_spool_path%"
```
and get error

```bash
php7.2 bin/console swiftmailer:spool:send --env=prod --mailer=default
 [2020-01-15 12:29:51] Processing default mailer spool...
In StreamBuffer.php line 277:
  Connection could not be established with host smtp.service.company.com [ #0]
```

However the telnet works with port 465. and If i remove the `encyption`,`auth_mode`, `port` and `stream-options`, it sends the mails, but puiting encyption configs get error.
