### ISSUE TITLE
Send mails with RabbitMQ Bundle consumer / disable email spooling temporarily

### ISSUE THREAD

**Issue by esynaps** [swiftmailer/swiftmailer#1247]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| RFC?                | no
| How used?           | Symfony
| Swiftmailer version | 5.4.12
| PHP version         | 7.2

**This post is only to help people who may have had the same problem as me**

### Observed behaviour

Emails are not sent when using spooling and calling the send() method in a symfony command service (i.e. a consumer for RabbitMQBundle).

```
# SwiftMailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
```

I tried to inject EmailSenderListener  in the constructor of my service/consumer

```
    public function __construct(\Swift_Mailer $mailer, EmailSenderListener $emailSenderListener)
    {
        $this->mailer = $mailer;
        $this->emailSenderListener = $emailSenderListener;
    }
```

and after :
```
$this->mailer->send($message)
```
these 2 lines :
```
$this->emailSenderListener->onTerminate();
$this->mailer->getTransport()->stop();
```

But now, after several send successfully, I got the error
```
Symfony\Component\Debug\Exception\ContextErrorException: Notice: fwrite(): send of 114 bytes f
ailed with errno=10053 Une connexion tablie a t abandonne par un logiciel de votre ordinateur
hte.
 in C:\www\X\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:240
````
