### ISSUE TITLE
SpoolTransport's event system creates memory leaks

### ISSUE THREAD

**Issue by proArtex** [swiftmailer/swiftmailer#1294]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Symfony
| Swiftmailer version | 6.2.3
| PHP version         | 7.4

### Observed behaviour

I am using enqueue bundle with long-living consumer along with monolog bundle (swift_mailer handler). I detected a memory leak caused by commented lines of the send() method:

```php
public function send(Swift_Mime_SimpleMessage $message, &$failedRecipients = null)
    {
//        if ($evt = $this->eventDispatcher->createSendEvent($this, $message)) {
//            $this->eventDispatcher->dispatchEvent($evt, 'beforeSendPerformed');
//            if ($evt->bubbleCancelled()) {
//                return 0;
//            }
//        }

        $success = $this->spool->queueMessage($message);

//        if ($evt) {
//            $evt->setResult($success ? Swift_Events_SendEvent::RESULT_SPOOLED : Swift_Events_SendEvent::RESULT_FAILED);
//            $this->eventDispatcher->dispatchEvent($evt, 'sendPerformed');
//        }

        return 1;
    }
```
The problem isn’t in memory consumption only, but in slowing down every next iteration. Basically what happens is garbage collector tries to remove object references each time “possible roots” buffer has more than 10k references. Since we add more and more objects each consumer’s iteration, php runs GC all the time and removes nothing. The more references we have in the buffer, the longer it takes to go through it (multiple times per request).

### Expected behaviour

Removing unused refernces

### Example

I've noticed that because I am using sort of RPC and send hundreds of messages into a queue awaiting response. Just send as many messages as you can generating any logs, and you will notice every http request is processed slower and slower.

```yaml
# config/packages/swiftmailer.yaml
swiftmailer:
    url: ...
    spool:
        type: file
        path: ...
```

```yaml
# config/packages/monolog.yaml
monolog:
    handlers:
        swift:
            type: swift_mailer
            from_email: ...
            to_email: ...
            subject: ...
            level: ...
            formatter: monolog.formatter.html
            content_type: text/html
```

P.S.: It seems like this issue has been here for a long time: https://stackoverflow.com/questions/21617163/memory-leak-with-symfony2-swiftmailer
