### ISSUE TITLE
Swift Mailer file spool + antiflood

### ISSUE THREAD

**Issue by dorian53** [swiftmailer/swiftmailer#863]
Hello,

Objective: to timing the sending of e-mails 20 / seconds.
Context: e-mails are put in a queue and then sent via the command **swiftmailer:spool:send**.

Test, with this configuration 2 e-mails / minute.

```
...
            spool:
                type: file
                path: "%storage_dir%spool/"
            antiflood:
                threshold: 2
                sleep: 60
```

Controller :

```
        /* @var $mailer \Swift_Mailer */
        $mailer = $this->get('swiftmailer.mailer...');
        for ($i = 1; $i <= 4; $i++) {
            $message = \Swift_Message::newInstance();
            $message->setSubject('Message n°' . $i);
            $message->setBody('TEST');
            $message->addTo('...');
            $message->addFrom('....');
            $mailer->send($message);
        }
```

The command **swiftmailer:spool:send** cadence well sent to 2 e-mails / minute but problem the controller's code also waits 60 seconds.

The _sleep_ configuration should not apply to the controller in the case of a _file_ type spool?

What do you think ?

In controller, is it possible to do that :

```
    $spool = $mailer->getTransport()->getSpool();
    ...
    $spool->queueMessage($message);
```

But code in controller is specific and no depends on the config.

Can anyone confirm that the bundle incorrectly implements the concept of antiflood with file type spool ?

Thank you.

**Edit**

I posted in _symfony/swiftmailer-bundle_ and on I advised to post here :
- https://github.com/symfony/swiftmailer-bundle/issues/151
